# try: the try block let us test a block of code for errors
# the except block lets lets us handle the execution

# x="i am the best in the world, i am the phenomenal"
# try:
#     print(x+5)
# except:
#     pass
#     # print("i am the best in the world")
#
#
#     # MANY EXCEPTION
# try:
#     print(x+5)
# except NameError:
#     print("variable is not defined")
# except:
#     print("something else went wrong")




     # ELSE KEYWORD
# try:
#     print("hello")
# except:
#     print("something went to wrong")
# else:
#     print("nothing went to wrong")
#
# try:
#     print("x")
# except:
#     print("something went to wrong")
# finally:
#     print("the 'try except' is finished")

# try:
#     f=open("demofile")
#     f.write("when we say sorry its doesn't mean that we are wrong it just mean that ")
#
# except:
#      print("something went to wrong when writing the file")
# finally:
#     f.close()


     # RAISE AN ERROR

#
# x=int(input())
# if x<0:
#     raise Exception("sorry, no number below zero")

# x="hello"
# print(type(x))
# if type(x) is not int:
#     raise Exception("only integers are allows")
